19:18:33 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:18:40 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

19:18:57 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:23:23 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:23:26 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

19:23:34 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:24:47 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:24:55 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:25:19 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:26:28 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:26:28 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.

19:26:29 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:26:29 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:26:30 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:26:46 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:26:46 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.

19:26:47 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:26:47 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:28:26 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:28:29 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

19:29:26 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:30:55 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:31:49 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:32:00 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.

19:32:16 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:32:22 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:32:26 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:35:15 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:35:17 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

19:35:24 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:35:26 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:35:28 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:35:30 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:52:29 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:52:29 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.

19:52:30 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:52:30 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:52:31 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:56:17 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

19:56:20 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

19:56:27 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:56:28 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

19:57:54 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

19:57:54 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 133
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

19:57:55 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

19:57:55 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:01:33 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:01:35 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:01:54 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:01:54 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:01:55 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:01:55 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:02:04 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:04:16 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:04:19 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:04:26 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:04:47 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:04:48 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:04:48 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:05:14 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:05:15 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:05:15 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:05:21 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:05:29 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:05:31 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:09:46 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:09:46 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:09:47 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:09:47 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:10:12 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:10:14 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:10:14 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:10:19 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:10:32 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:10:37 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:10:39 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:10:42 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:12:23 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:12:23 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:12:24 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:12:24 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:12:32 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:12:43 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:15:24 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:15:27 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:15:44 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:15:44 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:15:45 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:15:45 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:15:47 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:27:00 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:27:03 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:27:10 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:27:17 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:27:35 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:27:35 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:27:37 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:27:37 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:27:41 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:29:50 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:29:52 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:29:59 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:30:00 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:30:36 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:30:36 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에 데이터를 쓸 수 없습니다.   위치: System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   위치: System.IO.Stream.<BeginEndWriteAsync>b__16(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   위치: System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   위치: System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   위치: DY.NET.ASocketCover.<WriteAsync>d__0.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 55
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 137
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:30:37 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:30:37 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:30:41 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:36:43 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:36:46 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:36:57 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:36:58 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:36:58 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

20:36:58 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:36:58 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 프로토콜 에러 발생: HEADER_COMPANY_ID

20:36:59 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 프로토콜 에러 발생: HEADER_COMPANY_ID

20:37:14 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에서 데이터를 읽을 수 없습니다.   위치: System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   위치: System.IO.Stream.<BeginEndReadAsync>b__e(Stream stream, IAsyncResult asyncResult)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<ReadAsync>d__4.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 65
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<WaitResponsePostAsync>d__9.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 106
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 144
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:37:15 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:45:41 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:45:42 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:45:45 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:45:52 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:49:47 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:49:50 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:49:56 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:58:29 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

20:58:32 DY.WPF.CommConnectionDataGrid
시도 결과: It was successfully connected.

20:58:42 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:58:44 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:58:56 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:59:01 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

20:59:37 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

20:59:51 DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT
Tcp 192.168.10.150:2004 UpdateIOAsync 예외처리 메세지는 이하와 같음: 전송 연결 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다에서 데이터를 읽을 수 없습니다.   위치: System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   위치: System.IO.Stream.<BeginEndReadAsync>b__e(Stream stream, IAsyncResult asyncResult)
   위치: System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<ReadAsync>d__4.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 65
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.NET.ASocketCover.<WaitResponsePostAsync>d__9.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 102
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   위치: DY.NET.ASocketCover.<PostAsync>d__d.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.NET\PLC\ASocketCover.cs:줄 140
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   위치: DY.WPF.SYSTEM.COMM.CommIOMonitoringXGT.<UpdateIOAsync>d__7.MoveNext() 파일 c:\Users\CHILD\GitHub\DY\DY.WPF\SYSTEM\COMM\IO\CommIOMonitoringXGT.cs:줄 99

20:59:52 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

21:00:24 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

21:00:24 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

21:00:24 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

21:01:00 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

21:01:09 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

21:01:14 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

21:01:23 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

21:01:29 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

21:01:30 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

21:01:31 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 종료

21:02:04 DY.WPF.SYSTEM.COMM.ACommIOMonitoringStrategy
Tcp 192.168.10.150:2004 업데이트 루프 시작

21:02:04 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속 해제

21:02:04 DY.NET.LSIS.XGT.XGTFEnetSocket
LSIS XGT FEnet(192.168.10.150:2004) 이더넷 통신 동기 접속

